// Code generated by MockGen. DO NOT EDIT.
// Source: rss_parrot/logic (interfaces: ISummaryRetrier)
//
// Generated by this command:
//
//	mockgen --build_flags=--mod=mod -destination ../test/mocks/mock_summary_retrier.go -package mocks rss_parrot/logic ISummaryRetrier
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockISummaryRetrier is a mock of ISummaryRetrier interface.
type MockISummaryRetrier struct {
	ctrl     *gomock.Controller
	recorder *MockISummaryRetrierMockRecorder
	isgomock struct{}
}

// MockISummaryRetrierMockRecorder is the mock recorder for MockISummaryRetrier.
type MockISummaryRetrierMockRecorder struct {
	mock *MockISummaryRetrier
}

// NewMockISummaryRetrier creates a new mock instance.
func NewMockISummaryRetrier(ctrl *gomock.Controller) *MockISummaryRetrier {
	mock := &MockISummaryRetrier{ctrl: ctrl}
	mock.recorder = &MockISummaryRetrierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockISummaryRetrier) EXPECT() *MockISummaryRetrierMockRecorder {
	return m.recorder
}

// QueueForRetry mocks base method.
func (m *MockISummaryRetrier) QueueForRetry(accountId int, statusId, articleText string, now time.Time) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "QueueForRetry", accountId, statusId, articleText, now)
}

// QueueForRetry indicates an expected call of QueueForRetry.
func (mr *MockISummaryRetrierMockRecorder) QueueForRetry(accountId, statusId, articleText, now any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueueForRetry", reflect.TypeOf((*MockISummaryRetrier)(nil).QueueForRetry), accountId, statusId, articleText, now)
}

// RetryNextDue mocks base method.
func (m *MockISummaryRetrier) RetryNextDue(now time.Time) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RetryNextDue", now)
	ret0, _ := ret[0].(bool)
	return ret0
}

// RetryNextDue indicates an expected call of RetryNextDue.
func (mr *MockISummaryRetrierMockRecorder) RetryNextDue(now any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RetryNextDue", reflect.TypeOf((*MockISummaryRetrier)(nil).RetryNextDue), now)
}

// Start mocks base method.
func (m *MockISummaryRetrier) Start() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Start")
}

// Start indicates an expected call of Start.
func (mr *MockISummaryRetrierMockRecorder) Start() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockISummaryRetrier)(nil).Start))
}
