// Code generated by MockGen. DO NOT EDIT.

package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockISummarizer is a mock of ISummarizer interface.
type MockISummarizer struct {
	ctrl     *gomock.Controller
	recorder *MockISummarizerMockRecorder
}

// MockISummarizerMockRecorder is the mock recorder for MockISummarizer.
type MockISummarizerMockRecorder struct {
	mock *MockISummarizer
}

// NewMockISummarizer creates a new mock instance.
func NewMockISummarizer(ctrl *gomock.Controller) *MockISummarizer {
	mock := &MockISummarizer{ctrl: ctrl}
	mock.recorder = &MockISummarizerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockISummarizer) EXPECT() *MockISummarizerMockRecorder {
	return m.recorder
}

// Summarize mocks base method.
func (m *MockISummarizer) Summarize(arg0 string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Summarize", arg0)
	ret0, _ := ret[0].(string)
	return ret0
}

// Summarize indicates an expected call of Summarize.
func (mr *MockISummarizerMockRecorder) Summarize(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Summarize", reflect.TypeOf((*MockISummarizer)(nil).Summarize), arg0)
}
