// Code generated by MockGen. DO NOT EDIT.
// Source: rss_parrot/logic (interfaces: IArticleExtractor)
//
// Generated by this command:
//
//	mockgen --build_flags=--mod=mod -destination ../test/mocks/mock_article_extractor.go -package mocks rss_parrot/logic IArticleExtractor
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"
	logic "rss_parrot/logic"

	gomock "go.uber.org/mock/gomock"
)

// MockIArticleExtractor is a mock of IArticleExtractor interface.
type MockIArticleExtractor struct {
	ctrl     *gomock.Controller
	recorder *MockIArticleExtractorMockRecorder
	isgomock struct{}
}

// MockIArticleExtractorMockRecorder is the mock recorder for MockIArticleExtractor.
type MockIArticleExtractorMockRecorder struct {
	mock *MockIArticleExtractor
}

// NewMockIArticleExtractor creates a new mock instance.
func NewMockIArticleExtractor(ctrl *gomock.Controller) *MockIArticleExtractor {
	mock := &MockIArticleExtractor{ctrl: ctrl}
	mock.recorder = &MockIArticleExtractorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIArticleExtractor) EXPECT() *MockIArticleExtractorMockRecorder {
	return m.recorder
}

// Extract mocks base method.
func (m *MockIArticleExtractor) Extract(articleUrl string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Extract", articleUrl)
	ret0, _ := ret[0].(string)
	return ret0
}

// Extract indicates an expected call of Extract.
func (mr *MockIArticleExtractorMockRecorder) Extract(articleUrl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Extract", reflect.TypeOf((*MockIArticleExtractor)(nil).Extract), articleUrl)
}

// ExtractArticle mocks base method.
func (m *MockIArticleExtractor) ExtractArticle(articleUrl string) logic.ExtractedArticle {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExtractArticle", articleUrl)
	ret0, _ := ret[0].(logic.ExtractedArticle)
	return ret0
}

// ExtractArticle indicates an expected call of ExtractArticle.
func (mr *MockIArticleExtractorMockRecorder) ExtractArticle(articleUrl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExtractArticle", reflect.TypeOf((*MockIArticleExtractor)(nil).ExtractArticle), articleUrl)
}
