// Code generated by MockGen. DO NOT EDIT.
// Source: rss_parrot/logic (interfaces: IMetrics)
//
// Generated by this command:
//
//	mockgen --build_flags=--mod=mod -destination ../test/mocks/mock_metrics.go -package mocks rss_parrot/logic IMetrics
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"
	logic "rss_parrot/logic"

	gomock "go.uber.org/mock/gomock"
)

// MockIMetrics is a mock of IMetrics interface.
type MockIMetrics struct {
	ctrl     *gomock.Controller
	recorder *MockIMetricsMockRecorder
	isgomock struct{}
}

// MockIMetricsMockRecorder is the mock recorder for MockIMetrics.
type MockIMetricsMockRecorder struct {
	mock *MockIMetrics
}

// NewMockIMetrics creates a new mock instance.
func NewMockIMetrics(ctrl *gomock.Controller) *MockIMetrics {
	mock := &MockIMetrics{ctrl: ctrl}
	mock.recorder = &MockIMetricsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIMetrics) EXPECT() *MockIMetricsMockRecorder {
	return m.recorder
}

// CheckableFeedCount mocks base method.
func (m *MockIMetrics) CheckableFeedCount(count int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "CheckableFeedCount", count)
}

// CheckableFeedCount indicates an expected call of CheckableFeedCount.
func (mr *MockIMetricsMockRecorder) CheckableFeedCount(count any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckableFeedCount", reflect.TypeOf((*MockIMetrics)(nil).CheckableFeedCount), count)
}

// CurrentConnections mocks base method.
func (m *MockIMetrics) CurrentConnections(count int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "CurrentConnections", count)
}

// CurrentConnections indicates an expected call of CurrentConnections.
func (mr *MockIMetricsMockRecorder) CurrentConnections(count any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CurrentConnections", reflect.TypeOf((*MockIMetrics)(nil).CurrentConnections), count)
}

// DbFileSize mocks base method.
func (m *MockIMetrics) DbFileSize(size int64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "DbFileSize", size)
}

// DbFileSize indicates an expected call of DbFileSize.
func (mr *MockIMetricsMockRecorder) DbFileSize(size any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DbFileSize", reflect.TypeOf((*MockIMetrics)(nil).DbFileSize), size)
}

// FeedRequested mocks base method.
func (m *MockIMetrics) FeedRequested(label string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "FeedRequested", label)
}

// FeedRequested indicates an expected call of FeedRequested.
func (mr *MockIMetricsMockRecorder) FeedRequested(label any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FeedRequested", reflect.TypeOf((*MockIMetrics)(nil).FeedRequested), label)
}

// FeedTootSent mocks base method.
func (m *MockIMetrics) FeedTootSent() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "FeedTootSent")
}

// FeedTootSent indicates an expected call of FeedTootSent.
func (mr *MockIMetricsMockRecorder) FeedTootSent() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FeedTootSent", reflect.TypeOf((*MockIMetrics)(nil).FeedTootSent))
}

// FeedUpdated mocks base method.
func (m *MockIMetrics) FeedUpdated() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "FeedUpdated")
}

// FeedUpdated indicates an expected call of FeedUpdated.
func (mr *MockIMetricsMockRecorder) FeedUpdated() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FeedUpdated", reflect.TypeOf((*MockIMetrics)(nil).FeedUpdated))
}

// NewPostSaved mocks base method.
func (m *MockIMetrics) NewPostSaved() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "NewPostSaved")
}

// NewPostSaved indicates an expected call of NewPostSaved.
func (mr *MockIMetricsMockRecorder) NewPostSaved() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewPostSaved", reflect.TypeOf((*MockIMetrics)(nil).NewPostSaved))
}

// PostsDeleted mocks base method.
func (m *MockIMetrics) PostsDeleted(count int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "PostsDeleted", count)
}

// PostsDeleted indicates an expected call of PostsDeleted.
func (mr *MockIMetricsMockRecorder) PostsDeleted(count any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PostsDeleted", reflect.TypeOf((*MockIMetrics)(nil).PostsDeleted), count)
}

// ServiceStarted mocks base method.
func (m *MockIMetrics) ServiceStarted() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ServiceStarted")
}

// ServiceStarted indicates an expected call of ServiceStarted.
func (mr *MockIMetricsMockRecorder) ServiceStarted() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ServiceStarted", reflect.TypeOf((*MockIMetrics)(nil).ServiceStarted))
}

// StartApubRequestIn mocks base method.
func (m *MockIMetrics) StartApubRequestIn(label string) logic.IRequestObserver {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartApubRequestIn", label)
	ret0, _ := ret[0].(logic.IRequestObserver)
	return ret0
}

// StartApubRequestIn indicates an expected call of StartApubRequestIn.
func (mr *MockIMetricsMockRecorder) StartApubRequestIn(label any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartApubRequestIn", reflect.TypeOf((*MockIMetrics)(nil).StartApubRequestIn), label)
}

// StartApubRequestOut mocks base method.
func (m *MockIMetrics) StartApubRequestOut(label string) logic.IRequestObserver {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartApubRequestOut", label)
	ret0, _ := ret[0].(logic.IRequestObserver)
	return ret0
}

// StartApubRequestOut indicates an expected call of StartApubRequestOut.
func (mr *MockIMetricsMockRecorder) StartApubRequestOut(label any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartApubRequestOut", reflect.TypeOf((*MockIMetrics)(nil).StartApubRequestOut), label)
}

// StartWebRequestIn mocks base method.
func (m *MockIMetrics) StartWebRequestIn(label string) logic.IRequestObserver {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartWebRequestIn", label)
	ret0, _ := ret[0].(logic.IRequestObserver)
	return ret0
}

// StartWebRequestIn indicates an expected call of StartWebRequestIn.
func (mr *MockIMetricsMockRecorder) StartWebRequestIn(label any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartWebRequestIn", reflect.TypeOf((*MockIMetrics)(nil).StartWebRequestIn), label)
}

// TootQueueLength mocks base method.
func (m *MockIMetrics) TootQueueLength(length int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "TootQueueLength", length)
}

// TootQueueLength indicates an expected call of TootQueueLength.
func (mr *MockIMetricsMockRecorder) TootQueueLength(length any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TootQueueLength", reflect.TypeOf((*MockIMetrics)(nil).TootQueueLength), length)
}

// TotalFollowers mocks base method.
func (m *MockIMetrics) TotalFollowers(count int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "TotalFollowers", count)
}

// TotalFollowers indicates an expected call of TotalFollowers.
func (mr *MockIMetricsMockRecorder) TotalFollowers(count any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TotalFollowers", reflect.TypeOf((*MockIMetrics)(nil).TotalFollowers), count)
}

// TotalPosts mocks base method.
func (m *MockIMetrics) TotalPosts(count int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "TotalPosts", count)
}

// TotalPosts indicates an expected call of TotalPosts.
func (mr *MockIMetricsMockRecorder) TotalPosts(count any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TotalPosts", reflect.TypeOf((*MockIMetrics)(nil).TotalPosts), count)
}
