// Code generated by MockGen. DO NOT EDIT.
// Source: rss_parrot/logic (interfaces: ISummarizer)
//
// Generated by this command:
//
//	mockgen --build_flags=--mod=mod -destination ../test/mocks/mock_summarizer.go -package mocks rss_parrot/logic ISummarizer
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockISummarizer is a mock of ISummarizer interface.
type MockISummarizer struct {
	ctrl     *gomock.Controller
	recorder *MockISummarizerMockRecorder
	isgomock struct{}
}

// MockISummarizerMockRecorder is the mock recorder for MockISummarizer.
type MockISummarizerMockRecorder struct {
	mock *MockISummarizer
}

// NewMockISummarizer creates a new mock instance.
func NewMockISummarizer(ctrl *gomock.Controller) *MockISummarizer {
	mock := &MockISummarizer{ctrl: ctrl}
	mock.recorder = &MockISummarizerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockISummarizer) EXPECT() *MockISummarizerMockRecorder {
	return m.recorder
}

// IsEnabled mocks base method.
func (m *MockISummarizer) IsEnabled() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsEnabled")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsEnabled indicates an expected call of IsEnabled.
func (mr *MockISummarizerMockRecorder) IsEnabled() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsEnabled", reflect.TypeOf((*MockISummarizer)(nil).IsEnabled))
}

// Summarize mocks base method.
func (m *MockISummarizer) Summarize(text string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Summarize", text)
	ret0, _ := ret[0].(string)
	return ret0
}

// Summarize indicates an expected call of Summarize.
func (mr *MockISummarizerMockRecorder) Summarize(text any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Summarize", reflect.TypeOf((*MockISummarizer)(nil).Summarize), text)
}

// TrimForSummary mocks base method.
func (m *MockISummarizer) TrimForSummary(text string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TrimForSummary", text)
	ret0, _ := ret[0].(string)
	return ret0
}

// TrimForSummary indicates an expected call of TrimForSummary.
func (mr *MockISummarizerMockRecorder) TrimForSummary(text any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TrimForSummary", reflect.TypeOf((*MockISummarizer)(nil).TrimForSummary), text)
}
