// Code generated by MockGen. DO NOT EDIT.
// Source: rss_parrot/logic (interfaces: IUserDirectory)
//
// Generated by this command:
//
//	mockgen --build_flags=--mod=mod -destination ../test/mocks/mock_user_director.go -package mocks rss_parrot/logic IUserDirectory
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"
	dto "rss_parrot/dto"

	gomock "go.uber.org/mock/gomock"
)

// MockIUserDirectory is a mock of IUserDirectory interface.
type MockIUserDirectory struct {
	ctrl     *gomock.Controller
	recorder *MockIUserDirectoryMockRecorder
	isgomock struct{}
}

// MockIUserDirectoryMockRecorder is the mock recorder for MockIUserDirectory.
type MockIUserDirectoryMockRecorder struct {
	mock *MockIUserDirectory
}

// NewMockIUserDirectory creates a new mock instance.
func NewMockIUserDirectory(ctrl *gomock.Controller) *MockIUserDirectory {
	mock := &MockIUserDirectory{ctrl: ctrl}
	mock.recorder = &MockIUserDirectoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIUserDirectory) EXPECT() *MockIUserDirectoryMockRecorder {
	return m.recorder
}

// AcceptFollower mocks base method.
func (m *MockIUserDirectory) AcceptFollower(followActId, followerUserUrl, followerInbox, followedUser string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AcceptFollower", followActId, followerUserUrl, followerInbox, followedUser)
	ret0, _ := ret[0].(error)
	return ret0
}

// AcceptFollower indicates an expected call of AcceptFollower.
func (mr *MockIUserDirectoryMockRecorder) AcceptFollower(followActId, followerUserUrl, followerInbox, followedUser any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AcceptFollower", reflect.TypeOf((*MockIUserDirectory)(nil).AcceptFollower), followActId, followerUserUrl, followerInbox, followedUser)
}

// GetFollowersSummary mocks base method.
func (m *MockIUserDirectory) GetFollowersSummary(user string) *dto.OrderedListSummary {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFollowersSummary", user)
	ret0, _ := ret[0].(*dto.OrderedListSummary)
	return ret0
}

// GetFollowersSummary indicates an expected call of GetFollowersSummary.
func (mr *MockIUserDirectoryMockRecorder) GetFollowersSummary(user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFollowersSummary", reflect.TypeOf((*MockIUserDirectory)(nil).GetFollowersSummary), user)
}

// GetFollowingSummary mocks base method.
func (m *MockIUserDirectory) GetFollowingSummary(user string) *dto.OrderedListSummary {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFollowingSummary", user)
	ret0, _ := ret[0].(*dto.OrderedListSummary)
	return ret0
}

// GetFollowingSummary indicates an expected call of GetFollowingSummary.
func (mr *MockIUserDirectoryMockRecorder) GetFollowingSummary(user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFollowingSummary", reflect.TypeOf((*MockIUserDirectory)(nil).GetFollowingSummary), user)
}

// GetOutboxSummary mocks base method.
func (m *MockIUserDirectory) GetOutboxSummary(user string) *dto.OrderedListSummary {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOutboxSummary", user)
	ret0, _ := ret[0].(*dto.OrderedListSummary)
	return ret0
}

// GetOutboxSummary indicates an expected call of GetOutboxSummary.
func (mr *MockIUserDirectoryMockRecorder) GetOutboxSummary(user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOutboxSummary", reflect.TypeOf((*MockIUserDirectory)(nil).GetOutboxSummary), user)
}

// GetUserInfo mocks base method.
func (m *MockIUserDirectory) GetUserInfo(user string) *dto.UserInfo {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserInfo", user)
	ret0, _ := ret[0].(*dto.UserInfo)
	return ret0
}

// GetUserInfo indicates an expected call of GetUserInfo.
func (mr *MockIUserDirectoryMockRecorder) GetUserInfo(user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserInfo", reflect.TypeOf((*MockIUserDirectory)(nil).GetUserInfo), user)
}

// GetUserStatus mocks base method.
func (m *MockIUserDirectory) GetUserStatus(user, statusId string) (*dto.Note, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserStatus", user, statusId)
	ret0, _ := ret[0].(*dto.Note)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserStatus indicates an expected call of GetUserStatus.
func (mr *MockIUserDirectoryMockRecorder) GetUserStatus(user, statusId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserStatus", reflect.TypeOf((*MockIUserDirectory)(nil).GetUserStatus), user, statusId)
}

// GetWebfinger mocks base method.
func (m *MockIUserDirectory) GetWebfinger(user string) *dto.WebfingerResp {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWebfinger", user)
	ret0, _ := ret[0].(*dto.WebfingerResp)
	return ret0
}

// GetWebfinger indicates an expected call of GetWebfinger.
func (mr *MockIUserDirectoryMockRecorder) GetWebfinger(user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWebfinger", reflect.TypeOf((*MockIUserDirectory)(nil).GetWebfinger), user)
}
