// Code generated by MockGen. DO NOT EDIT.
// Source: rss_parrot/dal (interfaces: IRepo)
//
// Generated by this command:
//
//	mockgen --build_flags=--mod=mod -destination ../test/mocks/mock_repo.go -package mocks rss_parrot/dal IRepo
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"
	dal "rss_parrot/dal"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockIRepo is a mock of IRepo interface.
type MockIRepo struct {
	ctrl     *gomock.Controller
	recorder *MockIRepoMockRecorder
	isgomock struct{}
}

// MockIRepoMockRecorder is the mock recorder for MockIRepo.
type MockIRepoMockRecorder struct {
	mock *MockIRepo
}

// NewMockIRepo creates a new mock instance.
func NewMockIRepo(ctrl *gomock.Controller) *MockIRepo {
	mock := &MockIRepo{ctrl: ctrl}
	mock.recorder = &MockIRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIRepo) EXPECT() *MockIRepoMockRecorder {
	return m.recorder
}

// AddAccountIfNotExist mocks base method.
func (m *MockIRepo) AddAccountIfNotExist(account *dal.Account, privKey string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddAccountIfNotExist", account, privKey)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddAccountIfNotExist indicates an expected call of AddAccountIfNotExist.
func (mr *MockIRepoMockRecorder) AddAccountIfNotExist(account, privKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddAccountIfNotExist", reflect.TypeOf((*MockIRepo)(nil).AddAccountIfNotExist), account, privKey)
}

// AddFeedPostIfNew mocks base method.
func (m *MockIRepo) AddFeedPostIfNew(accountId int, post *dal.FeedPost) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddFeedPostIfNew", accountId, post)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddFeedPostIfNew indicates an expected call of AddFeedPostIfNew.
func (mr *MockIRepoMockRecorder) AddFeedPostIfNew(accountId, post any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddFeedPostIfNew", reflect.TypeOf((*MockIRepo)(nil).AddFeedPostIfNew), accountId, post)
}

// AddFollower mocks base method.
func (m *MockIRepo) AddFollower(user string, follower *dal.FollowerInfo) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddFollower", user, follower)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddFollower indicates an expected call of AddFollower.
func (mr *MockIRepoMockRecorder) AddFollower(user, follower any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddFollower", reflect.TypeOf((*MockIRepo)(nil).AddFollower), user, follower)
}

// AddPendingSummaryIfNew mocks base method.
func (m *MockIRepo) AddPendingSummaryIfNew(ps *dal.PendingSummary) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddPendingSummaryIfNew", ps)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddPendingSummaryIfNew indicates an expected call of AddPendingSummaryIfNew.
func (mr *MockIRepoMockRecorder) AddPendingSummaryIfNew(ps any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddPendingSummaryIfNew", reflect.TypeOf((*MockIRepo)(nil).AddPendingSummaryIfNew), ps)
}

// AddToot mocks base method.
func (m *MockIRepo) AddToot(accountId int, toot *dal.Toot) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddToot", accountId, toot)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddToot indicates an expected call of AddToot.
func (mr *MockIRepoMockRecorder) AddToot(accountId, toot any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddToot", reflect.TypeOf((*MockIRepo)(nil).AddToot), accountId, toot)
}

// AddTootQueueItem mocks base method.
func (m *MockIRepo) AddTootQueueItem(tqi *dal.TootQueueItem) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddTootQueueItem", tqi)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddTootQueueItem indicates an expected call of AddTootQueueItem.
func (mr *MockIRepoMockRecorder) AddTootQueueItem(tqi any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddTootQueueItem", reflect.TypeOf((*MockIRepo)(nil).AddTootQueueItem), tqi)
}

// BruteDeleteAccount mocks base method.
func (m *MockIRepo) BruteDeleteAccount(accountId int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BruteDeleteAccount", accountId)
	ret0, _ := ret[0].(error)
	return ret0
}

// BruteDeleteAccount indicates an expected call of BruteDeleteAccount.
func (mr *MockIRepoMockRecorder) BruteDeleteAccount(accountId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BruteDeleteAccount", reflect.TypeOf((*MockIRepo)(nil).BruteDeleteAccount), accountId)
}

// DeleteHandledActivities mocks base method.
func (m *MockIRepo) DeleteHandledActivities(before time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteHandledActivities", before)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteHandledActivities indicates an expected call of DeleteHandledActivities.
func (mr *MockIRepoMockRecorder) DeleteHandledActivities(before any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteHandledActivities", reflect.TypeOf((*MockIRepo)(nil).DeleteHandledActivities), before)
}

// DeleteTootQueueItem mocks base method.
func (m *MockIRepo) DeleteTootQueueItem(id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTootQueueItem", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTootQueueItem indicates an expected call of DeleteTootQueueItem.
func (mr *MockIRepoMockRecorder) DeleteTootQueueItem(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTootQueueItem", reflect.TypeOf((*MockIRepo)(nil).DeleteTootQueueItem), id)
}

// DoesAccountExist mocks base method.
func (m *MockIRepo) DoesAccountExist(user string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DoesAccountExist", user)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DoesAccountExist indicates an expected call of DoesAccountExist.
func (mr *MockIRepoMockRecorder) DoesAccountExist(user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DoesAccountExist", reflect.TypeOf((*MockIRepo)(nil).DoesAccountExist), user)
}

// FinishPendingSummary mocks base method.
func (m *MockIRepo) FinishPendingSummary(statusId string, state dal.PendingSummaryState) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FinishPendingSummary", statusId, state)
	ret0, _ := ret[0].(error)
	return ret0
}

// FinishPendingSummary indicates an expected call of FinishPendingSummary.
func (mr *MockIRepoMockRecorder) FinishPendingSummary(statusId, state any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FinishPendingSummary", reflect.TypeOf((*MockIRepo)(nil).FinishPendingSummary), statusId, state)
}

// GetAccount mocks base method.
func (m *MockIRepo) GetAccount(user string) (*dal.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccount", user)
	ret0, _ := ret[0].(*dal.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccount indicates an expected call of GetAccount.
func (mr *MockIRepoMockRecorder) GetAccount(user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccount", reflect.TypeOf((*MockIRepo)(nil).GetAccount), user)
}

// GetAccountToCheck mocks base method.
func (m *MockIRepo) GetAccountToCheck(checkDue time.Time) (*dal.Account, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccountToCheck", checkDue)
	ret0, _ := ret[0].(*dal.Account)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetAccountToCheck indicates an expected call of GetAccountToCheck.
func (mr *MockIRepoMockRecorder) GetAccountToCheck(checkDue any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccountToCheck", reflect.TypeOf((*MockIRepo)(nil).GetAccountToCheck), checkDue)
}

// GetAccountsPage mocks base method.
func (m *MockIRepo) GetAccountsPage(offset, limit int) ([]*dal.Account, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccountsPage", offset, limit)
	ret0, _ := ret[0].([]*dal.Account)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetAccountsPage indicates an expected call of GetAccountsPage.
func (mr *MockIRepoMockRecorder) GetAccountsPage(offset, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccountsPage", reflect.TypeOf((*MockIRepo)(nil).GetAccountsPage), offset, limit)
}

// GetDistinctSharedInboxes mocks base method.
func (m *MockIRepo) GetDistinctSharedInboxes() ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDistinctSharedInboxes")
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDistinctSharedInboxes indicates an expected call of GetDistinctSharedInboxes.
func (mr *MockIRepoMockRecorder) GetDistinctSharedInboxes() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDistinctSharedInboxes", reflect.TypeOf((*MockIRepo)(nil).GetDistinctSharedInboxes))
}

// GetFeedFollowerCount mocks base method.
func (m *MockIRepo) GetFeedFollowerCount() (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFeedFollowerCount")
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFeedFollowerCount indicates an expected call of GetFeedFollowerCount.
func (mr *MockIRepoMockRecorder) GetFeedFollowerCount() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFeedFollowerCount", reflect.TypeOf((*MockIRepo)(nil).GetFeedFollowerCount))
}

// GetFeedLastUpdated mocks base method.
func (m *MockIRepo) GetFeedLastUpdated(accountId int) (time.Time, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFeedLastUpdated", accountId)
	ret0, _ := ret[0].(time.Time)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFeedLastUpdated indicates an expected call of GetFeedLastUpdated.
func (mr *MockIRepoMockRecorder) GetFeedLastUpdated(accountId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFeedLastUpdated", reflect.TypeOf((*MockIRepo)(nil).GetFeedLastUpdated), accountId)
}

// GetFollowerCount mocks base method.
func (m *MockIRepo) GetFollowerCount(user string, onlyApproved bool) (uint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFollowerCount", user, onlyApproved)
	ret0, _ := ret[0].(uint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFollowerCount indicates an expected call of GetFollowerCount.
func (mr *MockIRepoMockRecorder) GetFollowerCount(user, onlyApproved any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFollowerCount", reflect.TypeOf((*MockIRepo)(nil).GetFollowerCount), user, onlyApproved)
}

// GetFollowersById mocks base method.
func (m *MockIRepo) GetFollowersById(accountId int, onlyApproved bool) ([]*dal.FollowerInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFollowersById", accountId, onlyApproved)
	ret0, _ := ret[0].([]*dal.FollowerInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFollowersById indicates an expected call of GetFollowersById.
func (mr *MockIRepoMockRecorder) GetFollowersById(accountId, onlyApproved any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFollowersById", reflect.TypeOf((*MockIRepo)(nil).GetFollowersById), accountId, onlyApproved)
}

// GetFollowersByUser mocks base method.
func (m *MockIRepo) GetFollowersByUser(user string, onlyApproved bool) ([]*dal.FollowerInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFollowersByUser", user, onlyApproved)
	ret0, _ := ret[0].([]*dal.FollowerInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFollowersByUser indicates an expected call of GetFollowersByUser.
func (mr *MockIRepoMockRecorder) GetFollowersByUser(user, onlyApproved any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFollowersByUser", reflect.TypeOf((*MockIRepo)(nil).GetFollowersByUser), user, onlyApproved)
}

// GetNextId mocks base method.
func (m *MockIRepo) GetNextId() uint64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNextId")
	ret0, _ := ret[0].(uint64)
	return ret0
}

// GetNextId indicates an expected call of GetNextId.
func (mr *MockIRepoMockRecorder) GetNextId() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNextId", reflect.TypeOf((*MockIRepo)(nil).GetNextId))
}

// GetPendingSummaryToRetry mocks base method.
func (m *MockIRepo) GetPendingSummaryToRetry(due time.Time) (*dal.PendingSummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPendingSummaryToRetry", due)
	ret0, _ := ret[0].(*dal.PendingSummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPendingSummaryToRetry indicates an expected call of GetPendingSummaryToRetry.
func (mr *MockIRepoMockRecorder) GetPendingSummaryToRetry(due any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPendingSummaryToRetry", reflect.TypeOf((*MockIRepo)(nil).GetPendingSummaryToRetry), due)
}

// GetPostCount mocks base method.
func (m *MockIRepo) GetPostCount(user string) (uint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPostCount", user)
	ret0, _ := ret[0].(uint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPostCount indicates an expected call of GetPostCount.
func (mr *MockIRepoMockRecorder) GetPostCount(user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPostCount", reflect.TypeOf((*MockIRepo)(nil).GetPostCount), user)
}

// GetPostsPage mocks base method.
func (m *MockIRepo) GetPostsPage(accountId, offset, limit int) ([]*dal.FeedPost, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPostsPage", accountId, offset, limit)
	ret0, _ := ret[0].([]*dal.FeedPost)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPostsPage indicates an expected call of GetPostsPage.
func (mr *MockIRepoMockRecorder) GetPostsPage(accountId, offset, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPostsPage", reflect.TypeOf((*MockIRepo)(nil).GetPostsPage), accountId, offset, limit)
}

// GetPrivKey mocks base method.
func (m *MockIRepo) GetPrivKey(user string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPrivKey", user)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPrivKey indicates an expected call of GetPrivKey.
func (mr *MockIRepoMockRecorder) GetPrivKey(user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPrivKey", reflect.TypeOf((*MockIRepo)(nil).GetPrivKey), user)
}

// GetToot mocks base method.
func (m *MockIRepo) GetToot(statusId string) (*dal.Toot, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetToot", statusId)
	ret0, _ := ret[0].(*dal.Toot)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetToot indicates an expected call of GetToot.
func (mr *MockIRepoMockRecorder) GetToot(statusId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetToot", reflect.TypeOf((*MockIRepo)(nil).GetToot), statusId)
}

// GetTootExtracts mocks base method.
func (m *MockIRepo) GetTootExtracts(accountId int) ([]*dal.Toot, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTootExtracts", accountId)
	ret0, _ := ret[0].([]*dal.Toot)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTootExtracts indicates an expected call of GetTootExtracts.
func (mr *MockIRepoMockRecorder) GetTootExtracts(accountId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTootExtracts", reflect.TypeOf((*MockIRepo)(nil).GetTootExtracts), accountId)
}

// GetTootQueueItems mocks base method.
func (m *MockIRepo) GetTootQueueItems(aboveId, maxCount int) ([]*dal.TootQueueItem, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTootQueueItems", aboveId, maxCount)
	ret0, _ := ret[0].([]*dal.TootQueueItem)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetTootQueueItems indicates an expected call of GetTootQueueItems.
func (mr *MockIRepoMockRecorder) GetTootQueueItems(aboveId, maxCount any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTootQueueItems", reflect.TypeOf((*MockIRepo)(nil).GetTootQueueItems), aboveId, maxCount)
}

// GetTotalPostCount mocks base method.
func (m *MockIRepo) GetTotalPostCount() (uint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTotalPostCount")
	ret0, _ := ret[0].(uint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTotalPostCount indicates an expected call of GetTotalPostCount.
func (mr *MockIRepoMockRecorder) GetTotalPostCount() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTotalPostCount", reflect.TypeOf((*MockIRepo)(nil).GetTotalPostCount))
}

// InitUpdateDb mocks base method.
func (m *MockIRepo) InitUpdateDb() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "InitUpdateDb")
}

// InitUpdateDb indicates an expected call of InitUpdateDb.
func (mr *MockIRepoMockRecorder) InitUpdateDb() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InitUpdateDb", reflect.TypeOf((*MockIRepo)(nil).InitUpdateDb))
}

// MarkActivityHandled mocks base method.
func (m *MockIRepo) MarkActivityHandled(id string, when time.Time) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkActivityHandled", id, when)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MarkActivityHandled indicates an expected call of MarkActivityHandled.
func (mr *MockIRepoMockRecorder) MarkActivityHandled(id, when any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkActivityHandled", reflect.TypeOf((*MockIRepo)(nil).MarkActivityHandled), id, when)
}

// PurgePostsAndToots mocks base method.
func (m *MockIRepo) PurgePostsAndToots(accountId int, fromBefore time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PurgePostsAndToots", accountId, fromBefore)
	ret0, _ := ret[0].(error)
	return ret0
}

// PurgePostsAndToots indicates an expected call of PurgePostsAndToots.
func (mr *MockIRepoMockRecorder) PurgePostsAndToots(accountId, fromBefore any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PurgePostsAndToots", reflect.TypeOf((*MockIRepo)(nil).PurgePostsAndToots), accountId, fromBefore)
}

// RemoveFollower mocks base method.
func (m *MockIRepo) RemoveFollower(user, followerUserUrl string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveFollower", user, followerUserUrl)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveFollower indicates an expected call of RemoveFollower.
func (mr *MockIRepoMockRecorder) RemoveFollower(user, followerUserUrl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveFollower", reflect.TypeOf((*MockIRepo)(nil).RemoveFollower), user, followerUserUrl)
}

// ReschedulePendingSummary mocks base method.
func (m *MockIRepo) ReschedulePendingSummary(statusId string, attempts int, nextRetryDue time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReschedulePendingSummary", statusId, attempts, nextRetryDue)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReschedulePendingSummary indicates an expected call of ReschedulePendingSummary.
func (mr *MockIRepoMockRecorder) ReschedulePendingSummary(statusId, attempts, nextRetryDue any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReschedulePendingSummary", reflect.TypeOf((*MockIRepo)(nil).ReschedulePendingSummary), statusId, attempts, nextRetryDue)
}

// SetFollowerApproveStatus mocks base method.
func (m *MockIRepo) SetFollowerApproveStatus(user, followerUserUrl string, status int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetFollowerApproveStatus", user, followerUserUrl, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetFollowerApproveStatus indicates an expected call of SetFollowerApproveStatus.
func (mr *MockIRepoMockRecorder) SetFollowerApproveStatus(user, followerUserUrl, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetFollowerApproveStatus", reflect.TypeOf((*MockIRepo)(nil).SetFollowerApproveStatus), user, followerUserUrl, status)
}

// UpdateAccountFeedTimes mocks base method.
func (m *MockIRepo) UpdateAccountFeedTimes(accountId int, lastUpdated, nextCheckDue time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAccountFeedTimes", accountId, lastUpdated, nextCheckDue)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateAccountFeedTimes indicates an expected call of UpdateAccountFeedTimes.
func (mr *MockIRepoMockRecorder) UpdateAccountFeedTimes(accountId, lastUpdated, nextCheckDue any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAccountFeedTimes", reflect.TypeOf((*MockIRepo)(nil).UpdateAccountFeedTimes), accountId, lastUpdated, nextCheckDue)
}

// UpdateTootContent mocks base method.
func (m *MockIRepo) UpdateTootContent(statusId, content string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTootContent", statusId, content)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTootContent indicates an expected call of UpdateTootContent.
func (mr *MockIRepoMockRecorder) UpdateTootContent(statusId, content any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTootContent", reflect.TypeOf((*MockIRepo)(nil).UpdateTootContent), statusId, content)
}

// Vacuum mocks base method.
func (m *MockIRepo) Vacuum() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Vacuum")
	ret0, _ := ret[0].(error)
	return ret0
}

// Vacuum indicates an expected call of Vacuum.
func (mr *MockIRepoMockRecorder) Vacuum() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Vacuum", reflect.TypeOf((*MockIRepo)(nil).Vacuum))
}
